spring:
  application:
    name: task-tracker
  profiles:
    active: local

security:
  jwt:
    issuer: task-tracker
    secret-key: ${JWT_SECRET_KEY:>= 64 bytes}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION_TIME}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION_TIME}
