spring:
  datasource:
    url: jdbc:postgresql://dev-db.company.com:5432/your-database-url
    username: your-db-username
    password: your-db-password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger

    operationsSorter: method
    tagsSorter: alpha

    display-request-duration: true

    try-it-out-enabled: true

server:
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    org.apatech: INFO

  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{30} - %msg%n"

app:
  cors:
    allowed-origins:
      - {your-allowed-origin-url}

security:
  jwt:
    issuer: task-tracker-api
    secret-key: ${JWT_SECRET_KEY:>= 64 bytes}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION_TIME}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION_TIME}